<%@ Page Title="Advanced Driving School - Replacement Temp Permit" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="ReplaceTempPermit.aspx.cs" Inherits="ReplaceTempPermit" %>
<%@ Register Src="~/LeftNav.ascx" TagName="ucLeftNav" TagPrefix="ucLN" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<div id="leftsidebar">
  <ucLN:ucLeftNav ID="ucLeftNavControl" runat="server" />
</div>
<div id="mainpagecontent">
  <br />
  <h1>How To Get a Replacement Temporary Permit</h1>
  <br />
  <h3>The infomation below was taken from the BMV</h3>
  <p class="small">IN ORDER TO REDUCE TESTING REDUNDANCY AND SOME OF THE CUSTOMER INCONVENIENCE, INDIVIDUALS WHO HAVE LOST A PORTION OF THEIR TEMPORARY INSTRUCTION PERMIT MAY OBTAIN A REPLACEMENT.  THE FOLLOWING RULES ARE APPLICABLE TO A CLASS “D” OPERATORS LICENSE ONLY:</p>
  <p class="small">1. THE CUSTOMER MUST PURCHASE A NEW TEMPORARY PERMIT PACKET TO INCLUDE THE ISSUANCE OF A NEW PICTURE INSTRUCTION CARD THROUGH THE DEPUTY REGISTRAR. TRANSACTION CODE IS “ RPL”, (REPLACEMENT).</p>
  <p class="small">2. THE CUSTOMER MUST RETURN TO THE EXAM STATION WHERE THE ORIGINAL PERMIT WAS VALIDATED TO HAVE THE PREVIOUS TEST SCORES VERIFIED.</p>
  <p class="small">3. THE EXAMINER WILL CONDUCT STATUS QUESTIONS AND THE VISION SCREENING AS WITH ANY OTHER TEMPORARY PERMIT APPLICATION.</p>
  <p class="small">4. IF THE PREVIOUS WRITTEN TEST SCORES CAN BE VERIFIED (EITHER THROUGH STS TEST RECORDS, PREVIOUS TEMPORARY PACKET, OR DAILY SIGN IN SHEETS), THE EXAMINER WILL SIGN DATE, AND SEAL THE NEW PERMIT (USING THE CURRENT DATE).  THE NEW PERMIT WILL DESIGNATE NEW ISSUE DATE AND THE ORIGINAL EXPIRATION DATE.  “RPL”  DESIGNATING REPLACEMENT WILL APPEAR ON THE PERMIT.</p>
  <p class="small">CUSTOMERS WHO DO NOT WISH TO RETAIN THE EXPIRATION DATE OF THE ORIGINAL TEMPORARY PERMIT, WILL PURCHASE A NEW PERMIT PACKET AND WILL FOLLOW NORMAL PROCEDURES. INDIVIDUALS WHO HAVE LOST THEIR DOCUMENTS CONTAINING THE TEST SCORES, SHOULD CONTACT THE DX OFFICE WHERE THE ORIGINAL WRITTEN EXAM WAS ADMINISTERED AND INQUIRE IF TEST SCORES ARE AVAILABLE.  IF THE SCORES ARE NOT AVAILABLE, CUSTOMER CANNOT BE ISSUED A REPLACEMENT.  THEY MUST PURCHASE ANOTHER TEMPORARY INSTRUCTION PERMIT PACKET AND FOLLOW NORMAL PROCEDURES.</p>
</div>
</asp:Content>
